import type { Project } from "@/types/project";
export const demoProjects: Project[] = [{
  id:"demo-salekhpos",slug:"salekhpos",category:"full-stack",status:"in-progress",featured:true,published:true,displayOrder:1,technologies:["Next.js","TypeScript","PostgreSQL","Kotlin","Swift"],
  translations:{
    en:{title:"SalekhPos",shortDescription:"A global multi-store point-of-sale platform for small, medium and large retailers.",overview:"A multi-platform retail system designed around centralized administration, store workflows, localization, reliability and scale.",problem:"Retail businesses often need multiple disconnected tools for sales, inventory, staff access and reporting.",solution:"One role-aware platform that serves stores of different sizes while preserving centralized control and consistent data.",myRole:"Product architecture, system design and implementation direction.",keyFeatures:"Multi-store management, role-based workflows, localized operation, inventory, reporting and cross-platform clients.",architecture:"Web, desktop and mobile clients backed by centralized cloud services and a multi-tenant data model.",challenges:"Balancing large-store capability with simplicity for smaller stores while keeping security and performance first-class concerns."},
    az:{title:"SalekhPos",shortDescription:"Kiçik, orta və böyük mağazalar üçün qlobal multi-store POS platforması.",overview:"Mərkəzləşdirilmiş idarəetmə, mağaza iş axınları, lokalizasiya, etibarlılıq və miqyaslanmaya fokuslanan multi-platform retail sistemi.",problem:"Mağazalar satış, anbar, əməkdaş icazələri və hesabat üçün çox vaxt bir-birindən ayrı sistemlər istifadə edir.",solution:"Müxtəlif ölçülü mağazaları dəstəkləyən və mərkəzi nəzarəti qoruyan vahid role-based platforma.",myRole:"Məhsul arxitekturası, sistem dizaynı və implementasiya istiqaməti."},
    ka:{title:"SalekhPos",shortDescription:"გლობალური multi-store POS პლატფორმა მცირე, საშუალო და დიდი საცალო ბიზნესებისთვის.",overview:"მრავალპლატფორმიანი retail სისტემა ცენტრალიზებული მართვის, ლოკალიზაციის, საიმედოობისა და მასშტაბირების პრინციპებით.",problem:"საცალო ბიზნესებს ხშირად სჭირდებათ ერთმანეთისგან განცალკევებული სისტემები გაყიდვებისთვის, მარაგებისთვის და თანამშრომლების მართვისთვის.",solution:"ერთი role-based პლატფორმა სხვადასხვა ზომის მაღაზიებისთვის ცენტრალიზებული კონტროლით.",myRole:"პროდუქტის არქიტექტურა, სისტემის დიზაინი და განხორციელების მიმართულება."}
  }
}];
